export const API_KEY = "fcfc0fad69a24c6803360f6493b84718";

export const CATEGORIES = [
  "",
  "general",
  "world",
  "nation",
  "business",
  "technology",
  "entertainment",
  "sports",
  "science",
  "health",
];

export const CODES_LANGUAGES = [
  { code: "", lang: "" },
  { code: "ar", lang: "Arabic" },
  { code: "de", lang: "German" },
  { code: "en", lang: "English" },
  { code: "es", lang: "Spanish" },
  { code: "fr", lang: "French" },
  { code: "he", lang: "Hebrew" },
  { code: "it", lang: "Italian" },
  { code: "nl", lang: "Dutch" },
  { code: "no", lang: "Norwegian" },
  { code: "pt", lang: "Portuguese" },
  { code: "ru", lang: "Russian" },
  { code: "sv", lang: "Swedish" },
  { code: "zh", lang: "Chinese" },
];

export const SORT_BY = ["", "publishedAt", "relevance"];

export const CODES_COUNTRIES = [
  { code: "", name: "" },
  { code: "au", name: "Australia" },
  { code: "br", name: "Brazil" },
  { code: "ca", name: "Canada" },
  { code: "cn", name: "China" },
  { code: "eg", name: "Egypt" },
  { code: "fr", name: "France" },
  { code: "de", name: "Germany" },
  { code: "gr", name: "Greece" },
  { code: "hk", name: "Hong Kong" },
  { code: "in", name: "India" },
  { code: "ie", name: "Ireland" },
  { code: "il", name: "Israel" },
  { code: "it", name: "Italy" },
  { code: "jp", name: "Japan" },
  { code: "nl", name: "Netherlands" },
  { code: "no", name: "Norway" },
  { code: "pe", name: "Peru" },
  { code: "pt", name: "Portugal" },
  { code: "ph", name: "Philippines" },
  { code: "ru", name: "Russia" },
  { code: "sg", name: "Singapore" },
  { code: "es", name: "Spain" },
  { code: "se", name: "Sweden" },
  { code: "ch", name: "Switzerland" },
  { code: "tw", name: "Taiwan" },
  { code: "ua", name: "Ukraine" },
  { code: "gb", name: "United Kingdom" },
  { code: "us", name: "United States" },
];
