export const API_KEY = "8811c0d61a9942f4bbfa4487b40b9be1";

export const CATEGORIES = [
  "",
  "business",
  "entertainment",
  "generalhealth",
  "science",
  "sports",
  "technology",
];

export const CODES_LANGUAGES = [
  { code: "", lang: "" },
  { code: "ar", lang: "Arabic" },
  { code: "de", lang: "German" },
  { code: "en", lang: "English" },
  { code: "es", lang: "Spanish" },
  { code: "fr", lang: "French" },
  { code: "he", lang: "Hebrew" },
  { code: "it", lang: "Italian" },
  { code: "nl", lang: "Dutch" },
  { code: "no", lang: "Norwegian" },
  { code: "pt", lang: "Portuguese" },
  { code: "ru", lang: "Russian" },
  { code: "sv", lang: "Swedish" },
  { code: "ud", lang: "Undefined" },
  { code: "zh", lang: "Chinese" },
];

export const SORT_BY = ["", "relevancy", "popularity", "publishedAt"];

export const CODES_COUNTRIES = [
  { code: "", name: "" },
  { code: "ae", name: "United Arab Emirates" },
  { code: "ar", name: "Argentina" },
  { code: "at", name: "Austria" },
  { code: "au", name: "Australia" },
  { code: "be", name: "Belgium" },
  { code: "bg", name: "Bulgaria" },
  { code: "br", name: "Brazil" },
  { code: "ca", name: "Canada" },
  { code: "ch", name: "Switzerland" },
  { code: "cn", name: "China" },
  { code: "co", name: "Colombia" },
  { code: "cu", name: "Cuba" },
  { code: "cz", name: "Czech Republic" },
  { code: "de", name: "Germany" },
  { code: "eg", name: "Egypt" },
  { code: "fr", name: "France" },
  { code: "gb", name: "United Kingdom" },
  { code: "gr", name: "Greece" },
  { code: "hk", name: "Hong Kong" },
  { code: "hu", name: "Hungary" },
  { code: "id", name: "Indonesia" },
  { code: "ie", name: "Ireland" },
  { code: "il", name: "Israel" },
  { code: "in", name: "India" },
  { code: "it", name: "Italy" },
  { code: "jp", name: "Japan" },
  { code: "kr", name: "South Korea" },
  { code: "lt", name: "Lithuania" },
  { code: "lv", name: "Latvia" },
  { code: "ma", name: "Morocco" },
  { code: "mx", name: "Mexico" },
  { code: "my", name: "Malaysia" },
  { code: "ng", name: "Nigeria" },
  { code: "nl", name: "Netherlands" },
  { code: "no", name: "Norway" },
  { code: "nz", name: "New Zealand" },
  { code: "ph", name: "Philippines" },
  { code: "pl", name: "Poland" },
  { code: "pt", name: "Portugal" },
  { code: "ro", name: "Romania" },
  { code: "rs", name: "Serbia" },
  { code: "ru", name: "Russia" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "se", name: "Sweden" },
  { code: "sg", name: "Singapore" },
  { code: "si", name: "Slovenia" },
  { code: "sk", name: "Slovakia" },
  { code: "th", name: "Thailand" },
  { code: "tr", name: "Turkey" },
  { code: "tw", name: "Taiwan" },
  { code: "ua", name: "Ukraine" },
  { code: "us", name: "United States" },
  { code: "ve", name: "Venezuela" },
  { code: "za", name: "South Africa" },
];
